### ISSUE TITLE
No permission need return

### ISSUE THREAD

**Issue by tqcenglish** [node-casbin/koa-authz#6]
https://github.com/node-casbin/koa-authz/blob/9ca6c22cdfeba285021dd12acb6d6557b58bfe45/authz.js#L18-L39

```  javascript
      if (!authzorizer.checkPermission()) {
        ctx.status = 403 // change to return ctx.status=403 ???
      }
      await next()
```

**Comment by nodece** [comment]
Hi @tqcenglish ,What's wrong with that?

**Comment by tqcenglish** [comment]
设置 403 无权限后不能继续执行 await next()， express-authz 中是直接返回了 https://github.com/node-casbin/express-authz/blob/b760aa43a78c79bbcd52f2333036b36d18f103a4/authz.js#L28。

**Comment by nodece** [comment]
@tqcenglish Can you make a PR to fix it?

**Comment by hsluoyz** [comment]
> 设置 403 无权限后不能继续执行 await next()， express-authz 中是直接返回了 [https://github.com/node-casbin/express-authz/blob/b760aa43a78c79bbcd52f2333036b36d18f103a4/authz.js#L28。](https://github.com/node-casbin/express-authz/blob/b760aa43a78c79bbcd52f2333036b36d18f103a4/authz.js#L28%E3%80%82)

Please modify it to English.

**Comment by hsluoyz** [comment]
@tqcenglish please send a PR to fix it.

**Comment by hsluoyz** [comment]
Fixed in: https://github.com/node-casbin/koa-authz/pull/7
