### ISSUE TITLE
Package is problematic on npm

### ISSUE THREAD

**Issue by FantasyNeurotic** [node-casbin/koa-authz#8]
### Package is problematic on npm.
- On the master  branch `if (!await authzorizer.checkPermission()) {
        ctx.status = 403
        return
      }`
- On the v2.0 `if (!await authzorizer.checkPermission()) {
        ctx.status = 403
      }`
- I install koa-authz@3.0.0 and it like v2.0

**Comment by nodece** [comment]
@FantasyNeurotic Thank you for your report!  Latest version has been released on npm.
